name: android
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - name: Ensure Gradle CLI
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-8.7-bin.zip -o gradle.zip
          unzip -q gradle.zip
          echo "$PWD/gradle-8.7/bin" >> $GITHUB_PATH
      - name: Generate wrapper if missing
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            gradle wrapper --gradle-version 8.7
          fi
      - name: Build debug
        run: ./gradlew --no-daemon assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: daemon-portal-debug-apk
          path: app/build/outputs/apk/debug/*.apk
